"""empty message

Revision ID: 20ecd349260f
Revises: d210e7b6c7ec
Create Date: 2023-06-11 03:35:08.660994

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20ecd349260f'
down_revision = 'd210e7b6c7ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('category', sa.Enum('FOOD_SERVICE', 'SALE', 'MANUFACTURING', 'TRANSPORTATION', 'AGRICULTURE', 'EDUCATION', 'CONSTRUNCTION', 'OFFICE_WORK', 'CONSULTING', 'OTHER', name='jobcategoryenum'), nullable=False))
    op.add_column('job_postings', sa.Column('renewaled_at', sa.DateTime(), nullable=False))
    op.add_column('job_postings', sa.Column('deadline', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'job_postings', 'locations', ['location_id'], ['id'])
    op.drop_column('job_postings', 'catetory')
    op.drop_column('job_postings', 'is_deleted')
    op.drop_column('job_postings', 'salary_year')
    op.drop_column('job_postings', 'salary_month')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_postings', sa.Column('salary_month', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('salary_year', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('job_postings', sa.Column('is_deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('job_postings', sa.Column('catetory', mysql.ENUM('FOOD_SERVICE', 'SALE', 'MANUFACTURING', 'TRANSPORTATION', 'AGRICULTURE', 'EDUCATION', 'CONSTRUNCTION', 'OFFICE_WORK', 'CONSULTING', 'OTHER'), nullable=False))
    op.drop_constraint(None, 'job_postings', type_='foreignkey')
    op.drop_column('job_postings', 'deadline')
    op.drop_column('job_postings', 'renewaled_at')
    op.drop_column('job_postings', 'category')
    # ### end Alembic commands ###
