import argparse
from os import getenv


getenv("DATABASE_URL")

DATABASE_HOST=getenv("DATABASE_HOST")
DATABASE_USERNAME=getenv("DATABASE_USERNAME")
DATABASE_PASSWORD= getenv("DATABASE_PASSWORD")
DATABASE_NAME=getenv("DATABASE_NAME")
envs = {
    "DATABASE_URL": f"mysql+pymysql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}",
    "ALLOW_ORIGINS": getenv("ALLOW_ORIGINS"),
    "ALLOW_METHODS": getenv("ALLOW_METHODS"),
    "ALLOW_HEADERS": getenv("ALLOW_HEADERS"),
    "ALLOW_CREDENTIALS": getenv("ALLOW_CREDENTIALS"),
}
config = argparse.Namespace(**envs)